export default [
    {
      coordinate: {
        latitude: 33.715073,
        longitude:-117.847754,
      },
      title: "Dr Yin-Jia Gong",
      phoneNumber: "714-881-7081",
      description: "",
      addressStreet: "1520 Brookhollow Drive Suite 36",
      addressCity: "Santa Ana",
      addressState: "California",
      addressZip: "92705",
      insurances: [
        'Aetna Choice POS II',
        'Aetna Savings Plus of CA',
  'Aetna Signature Administrators PPO',
  'BCBS Blue Card PPO',
  'Blue Shield CA Bronze 60 PPO SHOP',
  'Blue Shield CA Bronze Full PPO 4500',
  'Blue Shield CA PPO',
  'Blue Shield CA Silver 70 PPO',
  'BS CA Platinum 90 PPO',
  'CIGNA HMO',
  'CIGNA LocalPlus',
  'CIGNA Open Access Plus',
  'CIGNA PPO',
  'First Health PPO',
  'Health Net CA Individual and Family PPO',
  'Health Net CA PPO',
  'Health Net PureCare One EPO Individual & Family Plan',
  'Humana Choice POS',
  'Multiplan PPO',
  'PHCS PPO',
  'PHCS PPO Kaiser',
  'UHC Choice Plus POS',
  'UHC Navigate HMO',
  'UHC Navigate POS',
  'UHC Options PPO"',
  
      ],
    },
    {
      coordinate: {
        latitude:33.670699,
        longitude:-117.857688,
      },
      title: "Dr Larry GreenBerg",
      phoneNumber: "949-222-6662",
      description: "",
      addressStreet: "19200 Von Karman Avenue Suite 210",
      addressCity: "Irvine",
      addressState: "California",
      addressZip: "92612",
      insurances: [
        'Medicaid',
        'Medicare',
        'State financed health insurance plan other than Medicaid',
        'Private health insurance',
        'Military insurance (e.g., TRICARE)',
        ],
    },
    {
      coordinate: {
        latitude:33.70456,
        longitude:-117.828455,
      },
      title: "Dr William Crumpton",
      phoneNumber: "714-669-4466",
      description: "",
      addressStreet: "14642 Newport Avenue Suite 200",
      addressCity: "Tustin",
      addressState: "California",
      addressZip: "92780",
      insurances: [
  'Aetna: *569884',
  'Blue Cross: *1M1010',
  'Blue Shield: *00G270620',
  'CIGNA: 3238963017',
  'CIGNA Select: 3238963020',
  'Health Net: 3203036155',
  'Health Net Senior: 5147036155',
  'SCAN: 863-28444',
  'United Healthcare: *0183460143',
      ],
    },
    {
      coordinate: {
        latitude:33.878507,
        longitude:-117.984881,
      },
      title: "Dr Om Prakash",
      phoneNumber: "626-523-7869",
      description: "",
      addressStreet: "8510 Links Road",
      addressCity: "Buena Park",
      addressState: "California",
      addressZip: "90621",
      insurances: ["ask physician to see insurance"],
    },
    {
      coordinate: {
        latitude:33.648024,
        longitude:-117.834490,
      },
      title: "Dr Arde Anoshivani",
      phoneNumber:"949-476-2676",
      description: "",
      addressStreet: "4360 Campus Drive Suite 110",
      addressCity: "Newport Beach",
      addressState: "California",
      addressZip: "92660",
      insurances: [
        'American Republic Insurance Company',
        'Blue Shield of California',
        'Consolidated Health Plans',
        'First Health (Coventry Health Care)',
        'Health Net',
        'Highmark Blue Shield',
        'UnitedHealthOne',
      ],
    },
  
]